name: Release
on:
  push:
    branches:
      - main
jobs:
  bump:
    name: Bump & Release Draft
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.bump.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - uses: jefflinse/pr-semver-bump@v1
        name: Bump and Tag Version
        id: bump
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          with-v: true
          require-release-notes: true
          release-notes-prefix: -- begin release notes --
          release-notes-suffix: -- end release notes --
      - name: Create draft release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          omitDraftDuringUpdate: true
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          tag: ${{ steps.bump.outputs.version }}
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    needs: bump
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build script
        run: |
          npx -y esbuild src/index.ts --bundle --outfile=mesh.js --packages=external --format=esm

      - name: Release script
        uses: ncipollo/release-action@v1
        with:
          artifacts: "mesh.js"
          tag: ${{ needs.bump.outputs.tag }}
          draft: true
          omitDraftDuringUpdate: true
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true

  release:
    name: Make release no longer draft
    runs-on: ubuntu-latest
    needs: ["build", "bump"]
    steps:
      - name: Release binary
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.bump.outputs.tag }}
          draft: false
          allowUpdates: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          omitPrereleaseDuringUpdate: true